apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: 422220193514.dkr.ecr.ap-south-1.amazonaws.com/repo:latest
          name: guestbook-ui
          ports:
            - containerPort: 80